security:
  token-secret: devsecret
  token-prefix: Bearer
  token-header-string: Authorization
  token-life-time: 72000000L
  refresh-token-life-time: 30000000000L
  claims-role-field: roles

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
#  #primary database properties
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/lingvi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
  #inmemory database properties
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      jdbcUrl: jdbc:h2:mem:lingvi_db
      username: devuser
      password: devpassword
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop

#Identity providers
providers:
  google:
    client-id: 594971830551-lq21v3eoggpf1amdjslu4f822o19of9c.apps.googleusercontent.com
    client-secret: 3O2TJnWYNaSbfmL5bDuQppR7
    access-token-uri: https://www.googleapis.com/oauth2/v4/token
    user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo?alt=json


#Properties of dictionary module
dictionary:
  espeak-path: C:\Program Files (x86)\eSpeak\command_line\espeak.exe
  api:
    yandex:
      dictionary:
        api-key: dict.1.1.20190219T174546Z.65b1ce9dac5922a1.5fc8bad4b4abc2e02b4dc6eb81ed545055825bd2
        url: https://dictionary.yandex.net/api/v1/dicservice.json/lookup
      translate:
        api-key: trnsl.1.1.20190219T171715Z.3f4cb494eadb18aa.924a92e085a253d1b4b94520cb970ccb046f9f99
        url: https://translate.yandex.net/api/v1.5/tr.json/translate
    systran:
      api-key: a2764cc2-7509-47c0-aece-db869e9ca74c
      dictionaryUrl:
      translateUrl:
      lemma-url: https://api-platform.systran.net/nlp/morphology/extract/lemma
    google:
      api-key: AIzaSyCCdyhKPsOoP4VtkRHCnzVoHRrfted3SXE
      text-to-speech-url: https://texttospeech.googleapis.com/v1/text:synthesize

